In [1]:
# NumPy Arrays

In [2]:
import numpy as np

In [3]:
my_list = [1,2,3]

In [4]:
my_list

[1, 2, 3]

In [6]:
np.array(my_list)

array([1, 2, 3])

In [7]:
arr = np.array(my_list)

In [8]:
arr

array([1, 2, 3])

In [10]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [11]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(my_mat) # now cast as array, and get back a 2 dim array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,11,2) # added step, in this case 2, every other 

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.zeros(3) # 1 dim passed

array([0., 0., 0.])

In [18]:
np.zeros((5,5)) # pass it a tuple of zeros # note: the 2nd set of paran

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones(4) # single dim of ones 

array([1., 1., 1., 1.])

In [20]:
np.ones((2,3)) # tuple for 2 dim of ones 

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.linspace(0,5,10) 

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [22]:
np.linspace(0,5,25) # still 1 dim array, one set of brackets in output 

array([0.        , 0.20833333, 0.41666667, 0.625     , 0.83333333,
       1.04166667, 1.25      , 1.45833333, 1.66666667, 1.875     ,
       2.08333333, 2.29166667, 2.5       , 2.70833333, 2.91666667,
       3.125     , 3.33333333, 3.54166667, 3.75      , 3.95833333,
       4.16666667, 4.375     , 4.58333333, 4.79166667, 5.        ])

In [23]:
np.eye(4) # identity matricx, must be square, note tis a 2 dim array by the double brackets 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.random.rand(5) # common random, this ia a tupal

array([0.17517258, 0.26944014, 0.76972473, 0.86902028, 0.83148976])

In [26]:
np.random.rand(5,5) # 2 dim array

array([[0.81174936, 0.19687012, 0.20724585, 0.4025658 , 0.18795435],
       [0.08439658, 0.31253482, 0.35865655, 0.16140308, 0.77649502],
       [0.67502688, 0.15926056, 0.78269564, 0.09837904, 0.14143642],
       [0.85162244, 0.07924886, 0.4278524 , 0.93531048, 0.36109856],
       [0.22713345, 0.92735559, 0.85035056, 0.84787332, 0.48884636]])

In [28]:
np.random.randn(2) # from standard normal or gausian 

array([ 1.24195045, -0.98530591])

In [29]:
np.random.randn(4,4) # to make as a two dim array

array([[ 0.55790563, -0.39842991, -0.11921573, -0.00686424],
       [-0.36128871, -0.32847865,  1.68831263,  0.80429706],
       [ 2.14770479,  0.95327488,  0.70524157,  0.64970175],
       [-0.58415591,  0.63626213, -1.20439953, -0.15421675]])

In [30]:
np.random.randint(1,100) # 1 but not to 100 random intergers 

58

In [31]:
np.random.randint(1,100,10) # 10 in this case for size to fill out a rand array structure

array([41, 76, 33, 44, 58, 28, 59, 83, 23, 78])

In [32]:
arr = np.arange(25) # the following is an exercise 

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
ranarr = np.random.randint(0,50,10)

In [35]:
ranarr

array([11,  0, 33, 36, 42, 45,  1, 44, 17,  7])

In [36]:
# reshape method on the array, very common

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
arr.reshape(5,5) # as 2 di, 5 rows by 5 cols

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
# finding max and min values and or find index location

In [40]:
ranarr

array([11,  0, 33, 36, 42, 45,  1, 44, 17,  7])

In [43]:
ranarr.max() # max val within that array

45

In [44]:
ranarr.min()

0

In [45]:
ranarr # look to see the index value of where the max or min value is located 

array([11,  0, 33, 36, 42, 45,  1, 44, 17,  7])

In [46]:
ranarr.argmax() in the 5th pos stat from 0 is max value index local

5

In [47]:
ranarr.argmin()

1

In [49]:
arr.shape # indicates a 1 dim vector with 25 elements

(25,)

In [50]:
arr = arr.reshape(5,5)

In [51]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
arr.shape # note a reshapee, a check and its now a 2 dim matrix 

(5, 5)

In [53]:
arr.dtype # check the data type in the array

dtype('int64')

In [54]:
from numpy.random import randint # an alternative to the above coding

In [56]:
randint (2,10)

5