In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# add two arrays together

In [6]:
arr + arr # ADD - using std math sci 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
arr - arr # subtraction

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
arr * arr # multiplication

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [9]:
arr # array check

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
# scaler operations, in much the same way 

In [11]:
arr + 100 # adds 100 to every elements in the array, and it's also a view of sorts in memory

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [13]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [14]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [16]:
arr / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
# sometimes numpy will issue a warining instead of an error on certain mathmatical operations 

In [19]:
1/0 # error becuase you cant divide a number by zero

ZeroDivisionError: division by zero

In [20]:
arr / arr # do this with NumPy, and you get a warning, we divide a numpy arr by itself with the 1st element is 0

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [22]:
# NULL or nan ('not a number'), also 'nan' aka 'Not AN object'

In [23]:
1 / arr # this warning gives an inf (infinity)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [24]:
# also do array math with expoents, everything got squared in the array (view in memory)

In [25]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
# Universal Array Function, perform math ops and broadcast across the array

In [29]:
np.sqrt(arr)    # square root of array

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [30]:
np.exp(arr)    # calc the exponent

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [31]:
np.max(arr)    # max

10

In [32]:
np.min(arr) # min

0

In [35]:
np.sin(arr) # trig func like sine

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [36]:
np.cos(arr) # cosine

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [37]:
np.log(arr) # logrithmic, note warning on 0 but it kep processing through the rest 

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])