In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5] # this is slice notation, note: indexing starts at zero

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[5:]  # note; 5 here is an index of 6

array([ 5,  6,  7,  8,  9, 10])

In [9]:
# numpy arrays differ from python lists for their ability to broadcast

In [11]:
arr[0:5] = 100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
arr = np.arange(0,11) # reset the practice array

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
slice_of_arr = arr[0:6] # a slice like this is actually a view of the oringal array, how numpy is...

In [17]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [20]:
slice_of_arr[:] = 99

In [21]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [22]:
arr  # watch out, it mutated the slice but it also added/mutated the original arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
# to get around is need be, make a copy of the array and mod it and leave the orig alone

In [26]:
arr_copy = arr.copy()

In [27]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [28]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [29]:
arr_copy[:]=100

In [31]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [32]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [33]:
# indexing a 2d array or aka a matrix

In [34]:
import numpy as np

In [35]:
arr_2d = np.array([[5,10,5],[20,25,30],[35,40,45]])

In [36]:
arr_2d

array([[ 5, 10,  5],
       [20, 25, 30],
       [35, 40, 45]])

In [37]:
# double bracket format

In [38]:
# to grab the digit 5, in the 1st index of 0

In [40]:
arr_2d[0][0]   # row, then colomn format

5

In [44]:
arr_2d[0]

array([ 5, 10,  5])

In [45]:
# to get 25

In [46]:
arr_2d[1][1]

25

In [48]:
arr_2d[2][1]  # grab 40

40

In [49]:
# Single bracket notation , or comma single bracket notation, better one to use

In [50]:
arr_2d[2,1] # just get rid of the brackets and use comma internaly for the index

40

In [51]:
arr_2d   # grab 30 with single bracket comma

array([[ 5, 10,  5],
       [20, 25, 30],
       [35, 40, 45]])

In [52]:
arr_2d[1,2] # use this, as its more less prone to error 

30

In [53]:
# now if you want sub-matrices from this matrix 

In [54]:
# to get 10,15 and 25, 30... use slice notation and single comma bracket 

In [55]:
arr_2d

array([[ 5, 10,  5],
       [20, 25, 30],
       [35, 40, 45]])

In [56]:
arr_2d[:2,1:] # grab the first two rows minus column 1, then up to index 1 to the end (which is end of row 2)

array([[10,  5],
       [25, 30]])

In [57]:
# step through it to see with the 1st bracket comma

In [58]:
arr_2d[:2]

array([[ 5, 10,  5],
       [20, 25, 30]])

In [59]:
# more important form of selection used is conditional selection

In [60]:
arr = np.arange(1,11)

In [61]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
# if compare with boolean operators you can get a whole new boolean array 

In [64]:
arr > 5 # using a comparison operator on it 

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
# note the output is T and F Boolean, and note the TYPE (not shown here but in online training)

In [65]:
bool_arr = arr > 5    # save as a new array

In [66]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [67]:
arr[bool_arr] # note passing the new bool_arr into the array will output what was only a TRUE 

array([ 6,  7,  8,  9, 10])

In [68]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [70]:
arr[bool_arr] # use to index out or conditioanlly select from the array 

array([ 6,  7,  8,  9, 10])

In [71]:
arr[arr>5] # more condensed way to get her done, just passing in boolean array values like this quick method 

array([ 6,  7,  8,  9, 10])

In [72]:
arr[arr<3] # all elements less than 3

array([1, 2])

In [74]:
# exercise practice, create new array to practice on

In [75]:
arr_2d = np.arange(50).reshape(5,10)

In [76]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [77]:
# practice grabbing chuncks like 13,14 and 23,24

In [78]:
arr_2d[1:3] # run to check    # slice notation, go one more than you think you need

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [80]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])